apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  selector:
    app: ftps
  ports:
    - name: ftps21
      protocol: TCP
      port: 21
      targetPort: 21
    - name: ftps20
      protocol: TCP
      port: 20
      targetPort: 20
    - name: ftps30100
      protocol: TCP
      port: 30100
      targetPort: 30100
    - name: ftps30101
      protocol: TCP
      port: 30101
      targetPort: 30101
    - name: ftps30102
      protocol: TCP
      port: 30102
      targetPort: 30102
    - name: ftps30103
      protocol: TCP
      port: 30103
      targetPort: 30103
  type: LoadBalancer
  loadBalancerIP: 192.168.49.240
