apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    database: grafana
    user: cmarteau
    password: yo
    url: 192.168.49.240:8086
    jsonData:
      httpMode: GET
