apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend		
    spec:
      restartPolicy: Always
      containers:
      - name: wordpress
        image: wordpress:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
